---

- name: "log: Create {{ nrpe_log_file }}"
  ansible.builtin.file:
    state: touch
    access_time: preserve
    modification_time: preserve
    path: "{{ nrpe_log_file }}"
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: "{{ nrpe_log_file_mode }}"

# EOF
...
