---

- name: "nrpe: Remove {{ nrpe_conf_file }}"
  file:
    path: "{{ nrpe_conf_file }}"
    state: "absent"
  when: nrpe_conf_recreate|default(false)|bool

- name: "nrpe: Stat {{ nrpe_conf_file }}"
  stat:
    path: "{{ nrpe_conf_file }}"
  register: conf_file

- name: "nrpe: Create {{ nrpe_conf_file }}"
  command: "cp {{ nrpe_conf_file }}.sample {{ nrpe_conf_file }}"
  args:
    creates: "{{ nrpe_conf_file }}"
  when: not conf_file.stat.exists

- name: "nrpe: Chown {{ nrpe_conf_file }}"
  file:
    path: "{{ nrpe_conf_file }}"
    owner: "{{ nrpe_conf_owner }}"
    group: "{{ nrpe_conf_group }}"

- name: "nrpe: Configure items in {{ nrpe_conf_file }}"
  lineinfile:
    dest: "{{ nrpe_conf_file }}"
    regexp: "^\\s*#*\\s*{{ item.key }}"
    line: "{{ item.key }}={{ item.val }}"
    backup: "{{ nrpe_backup_conf }}"
  loop: "{{ nrpe_conf }}"
  when: item.present|default(true)
  notify: reload nrpe

- name: "nrpe: Remove items from {{ nrpe_conf_file }}"
  lineinfile:
    dest: "{{ nrpe_conf_file }}"
    regexp: "^\\s*#*\\s*{{ item.key }}"
    line: "# {{ item.key }}"
    backup: "{{ nrpe_backup_conf }}"
  loop: "{{ nrpe_conf }}"
  when: not item.present|default(true)
  notify: reload nrpe

- name: "nrpe: Create {{ nrpe_log_file }}"
  command: "touch {{ nrpe_log_file }}"
  args:
    creates: "{{ nrpe_log_file }}"
    warn: false

- name: "nrpe: chown and chmod {{ nrpe_log_file }}"
  file:
    path: "{{ nrpe_log_file }}"
    owner: "{{ nrpe_user }}"
    group: "{{ nrpe_group }}"
    mode: "{{ nrpe_log_file_mode }}"

# EOF
...
