---
- name: "Nrpe: Remove {{ nrpe_conf_file }}"
  ansible.builtin.file:
    path: "{{ nrpe_conf_file }}"
    state: absent
  when: nrpe_conf_recreate|default(false)|bool

- name: "Nrpe: Create {{ nrpe_conf_file }}"
  ansible.builtin.command:
    cmd: cp {{ nrpe_conf_file }}.sample {{ nrpe_conf_file }}
    creates: "{{ nrpe_conf_file }}"
  tags: nrpe_conf_create

- name: "Nrpe: Set owner and group of {{ nrpe_conf_file }}"
  ansible.builtin.file:
    path: "{{ nrpe_conf_file }}"
    owner: "{{ nrpe_conf_owner }}"
    group: "{{ nrpe_conf_group }}"

- name: "Nrpe: Configure items in {{ nrpe_conf_file }}"
  ansible.builtin.lineinfile:
    dest: "{{ nrpe_conf_file }}"
    regexp: ^\s*#*\s*{{ item.key }}\s*=(.*)$
    line: "{{ item.key }}={{ item.val }}"
    backup: "{{ nrpe_backup_conf }}"
  loop: "{{ nrpe_conf }}"
  when: item.present|default(true)
  notify: reload nrpe

- name: "Nrpe: Remove items from {{ nrpe_conf_file }}"
  ansible.builtin.lineinfile:
    backrefs: true
    dest: "{{ nrpe_conf_file }}"
    regexp: ^\s*#*\s*{{ item.key }}\s*=(.*)$
    line: "# {{ item.key }}=\\1"
    backup: "{{ nrpe_backup_conf }}"
  loop: "{{ nrpe_conf }}"
  when: not item.present|default(true)
  notify: reload nrpe

- name: "Nrpe: Create {{ nrpe_conf_file_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ nrpe_conf_file_dir }}"
    owner: "{{ nrpe_conf_owner }}"
    group: "{{ nrpe_conf_group }}"
    mode: "0755"

# EOF
