---
# handlers for nrpe

- name: Enable and start nrpe
  ansible.builtin.service:
    name: "{{ nrpe_service }}"
    state: started
    enabled: true

- name: Disable and stop nrpe
  ansible.builtin.service:
    name: "{{ nrpe_service }}"
    state: stopped
    enabled: false

- name: Restart nrpe
  ansible.builtin.service:
    name: "{{ nrpe_service }}"
    state: restarted
  when: nrpe_enable|bool

- name: Reload nrpe
  ansible.builtin.service:
    name: "{{ nrpe_service }}"
    state: reloaded
  when: nrpe_enable|bool

# EOF
