---
# handlers for nrpe

- name: enable and start nrpe
  service:
    name: "{{ nrpe_service }}"
    state: "started"
    enabled: true

- name: disable and stop nrpe
  service:
    name: "{{ nrpe_service }}"
    state: "stopped"
    enabled: false

- name: restart nrpe
  service:
    name: "{{ nrpe_service }}"
    state: "restarted"
  when: nrpe_enable

- name: reload nrpe
  service:
    name: "{{ nrpe_service }}"
    state: "reloaded"
  when: nrpe_enable

# EOF
...
